### ISSUE TITLE
Split cards not working properly

### ISSUE THREAD

**Issue by koalasthegreat** [koalasthegreat/AmoeboidBot#11]
Cards like Claim // Fame break the bot, yielding the following error:

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/home/pi/bots/AmoeboidBot/bot.py", line 495, in on_message
    normal_image_url = front_face["image_uris"]["normal"]
KeyError: 'image_uris'
```

Need to modify the query to look for this condition

**Comment by koalasthegreat** [comment]
Should be resolved in 6fa47ef9ff758f23de208008eed7c43b55629115
